(part "2SCR514RTL"
    (packageRef "2SCR514RTL")
    (interface
        (port "1" (symbPinId 1) (portName "B") (portType INOUT))
        (port "2" (symbPinId 2) (portName "E") (portType INOUT))
        (port "3" (symbPinId 3) (portName "C") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "755-2SCR514RTL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ROHM-Semiconductor/2SCR514RTL?qs=%2FKR40Cd6GUphgPCgvqkTFQ%3D%3D")
    (property "Manufacturer_Name" "ROHM Semiconductor")
    (property "Manufacturer_Part_Number" "2SCR514RTL")
    (property "Description" "NPN, SOT-346T, 80V 0.7A, Driver Transistor")
    (property "Datasheet_Link" "https://fscdn.rohm.com/en/products/databook/datasheet/discrete/transistor/bipolar/2scr514rtl-e.pdf")
    (property "symbolName1" "2SCR514RTL")
)
