(part "XC9236A33DMR-G"
    (packageRef "SOT95P280X130-5N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VSS") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CE/MODE") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VOUT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "LX") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "865-XC9236A33DMR-G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Torex-Semiconductor/XC9236A33DMR-G?qs=AsjdqWjXhJ%2FLrLAbQ2bz5Q%3D%3D")
    (property "Manufacturer_Name" "Torex")
    (property "Manufacturer_Part_Number" "XC9236A33DMR-G")
    (property "Description" "Switching Voltage Regulators 600mA PFM/PWM DCDC Converter")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/XC9236A33DMR-G.pdf")
    (property "symbolName1" "XC9236A33DMR-G")
)
