(part "SHT21"
    (packageRef "SON100P300X300X110-7N-D")
    (interface
        (port "1" (symbPinId 1) (portName "SDA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VSS") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VDD") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SCL") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "403-SHT21")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Sensirion/SHT21?qs=wWC4CIiyLaNbiIJO6bf9AA%3D%3D")
    (property "Manufacturer_Name" "Sensirion")
    (property "Manufacturer_Part_Number" "SHT21")
    (property "Description" "Sensor Humidity & Temp 2%RH I2C DFN6 SHT21, 8")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/DKDS-37/728928.pdf")
    (property "symbolName1" "SHT21")
)
