(part "G5RL-U1-E-DC3"
    (packageRef "G5RLU1E")
    (interface
        (port "1" (symbPinId 1) (portName "S+/R-") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "COM_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NO_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NO_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "COM_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "NC_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "S-/R+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "161")
    (property "Mouser_Part_Number" "653-G5RLU1EDC3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/G5RL-U1-E-DC3?qs=9CM3gX%252B2VGH2i8p8HDDMCw%3D%3D")
    (property "Manufacturer_Name" "Omron Electronics")
    (property "Manufacturer_Part_Number" "G5RL-U1-E-DC3")
    (property "Description" "General Purpose Relays 16A hi swtch curent latching relay")
    (property "Datasheet_Link" "https://omronfs.omron.com/en_US/ecb/products/pdf/en-g5rl_uk.pdf")
    (property "symbolName1" "G5RL-U1-E-DC3")
)
