(part "NR3015T1R5N"
    (packageRef "NR3015")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "963-NR3015T1R5N")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TAIYO-YUDEN/NR3015T1R5N?qs=PzICbMaShUe%252BYogdNjEJcQ%3D%3D")
    (property "Manufacturer_Name" "TAIYO YUDEN")
    (property "Manufacturer_Part_Number" "NR3015T1R5N")
    (property "Description" "TAIYO YUDEN - NR3015T1R5N - INDUCTOR, SHIELDED, 1.5UH, 1.8A, SMD")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-DGA11/2187054.pdf")
    (property "symbolName1" "NR3015T1R5N")
)
